/** Kinship Sync brand tokens — strict 6-color palette */
export const BrandTokens = {
  cream: '#F5EFE8',
  heritageGreen: '#5F6E3D',
  orange: '#E08433',
  sand: '#D6C8AF',
  rust: '#5D2413',
  golden: '#ECAB47',
} as const;

export const cream = BrandTokens.cream;
export const heritageGreen = BrandTokens.heritageGreen;
export const orange = BrandTokens.orange;
export const sand = BrandTokens.sand;
export const rust = BrandTokens.rust;
export const golden = BrandTokens.golden;

export const Colors = {
  light: {
    text: rust,
    textSecondary: heritageGreen,
    textMuted: heritageGreen,
    textLight: cream,
    textDarkContrast: heritageGreen,
    background: cream,
    backgroundPrimary: cream,
    backgroundSecondary: sand,
    backgroundLight: cream,
    backgroundPaper: cream,
    neutralBg: sand,
    buttonPrimary: orange,
    primary: heritageGreen,
    primaryContrastText: cream,
    accent: golden,
    accentContrastText: rust,
    accentHighlight: golden,
    tint: heritageGreen,
    icon: heritageGreen,
    tabIconDefault: sand,
    tabIconSelected: heritageGreen,
    border: sand,
    divider: sand,
    success: heritageGreen,
    successContrastText: cream,
    error: rust,
    danger: rust,
    errorContrastText: cream,
    warning: golden,
    warningContrastText: rust,
    info: orange,
    infoContrastText: cream,
    primaryLight: sand,
    successLight: sand,
    warningLight: sand,
    infoLight: sand,
    errorLight: sand,
    dangerLight: sand,
    secondary: orange,
    secondaryLight: sand,
    tertiary: golden,
    tertiaryLight: sand,
    grey: sand,
  },
  dark: {
    text: cream,
    textSecondary: sand,
    textMuted: sand,
    textLight: rust,
    textDarkContrast: cream,
    background: rust,
    backgroundPrimary: rust,
    backgroundSecondary: heritageGreen,
    backgroundLight: rust,
    backgroundPaper: heritageGreen,
    neutralBg: heritageGreen,
    buttonPrimary: orange,
    primary: heritageGreen,
    primaryContrastText: cream,
    accent: golden,
    accentContrastText: rust,
    accentHighlight: golden,
    tint: heritageGreen,
    icon: sand,
    tabIconDefault: sand,
    tabIconSelected: golden,
    border: heritageGreen,
    divider: heritageGreen,
    success: heritageGreen,
    successContrastText: cream,
    error: orange,
    danger: orange,
    errorContrastText: rust,
    warning: golden,
    warningContrastText: rust,
    info: orange,
    infoContrastText: rust,
    primaryLight: sand,
    successLight: sand,
    warningLight: sand,
    infoLight: sand,
    errorLight: sand,
    dangerLight: sand,
    secondary: orange,
    secondaryLight: sand,
    tertiary: golden,
    tertiaryLight: sand,
    grey: sand,
  },
};
