export interface LegalSubsection {
  title: string;
  paragraphs: string[];
}

export interface LegalSection {
  title: string;
  paragraphs?: string[];
  list?: string[];
  subsections?: LegalSubsection[];
}

export interface LegalDocument {
  slug: string;
  title: string;
  subtitle: string;
  metaDescription: string;
  effectiveDate: string;
  intro?: string;
  sections: LegalSection[];
  contactEmail: string;
  footerNote?: string;
}

export const privacyPolicyDocument: LegalDocument = {
  slug: 'privacy-policy',
  title: 'Privacy Policy',
  subtitle: 'KinshipSync Mobile & Web Application',
  metaDescription:
    'Learn how KinshipSync collects, uses, and protects your personal information across our mobile and web platforms.',
  effectiveDate: '2025-08-03',
  intro:
    'This privacy policy applies to the KinshipSync app (hereby referred to as "Application") for mobile devices and the KinshipSync web platform that was created by Elropheka (hereby referred to as "Service Provider") as a Freemium service. This service is intended for use "AS IS".',
  contactEmail: 'kinshipsync@gmail.com',
  footerNote: 'This privacy policy page was generated by App Privacy Policy Generator',
  sections: [
    {
      title: 'Information Collection and Use',
      paragraphs: [
        'The Application collects information when you download and use it. This information may include information such as:',
      ],
      list: [
        "Your device's Internet Protocol address (e.g. IP address)",
        'The pages of the Application that you visit, the time and date of your visit, the time spent on those pages',
        'The time spent on the Application',
        'The operating system you use on your mobile device',
      ],
      subsections: [
        {
          title: 'Location Data',
          paragraphs: [
            "The Application collects your device's location, which helps the Service Provider determine your approximate geographical location and make use of in below ways:",
          ],
        },
        {
          title: 'Geolocation Services',
          paragraphs: [
            'The Service Provider utilizes location data to provide features such as personalized content, relevant recommendations, and location-based services.',
          ],
        },
        {
          title: 'Analytics and Improvements',
          paragraphs: [
            'Aggregated and anonymized location data helps the Service Provider to analyze user behavior, identify trends, and improve the overall performance and functionality of the Application.',
          ],
        },
        {
          title: 'Third-Party Services',
          paragraphs: [
            'Periodically, the Service Provider may transmit anonymized location data to external services. These services assist them in enhancing the Application and optimizing their offerings.',
            'The Service Provider may use the information you provided to contact you from time to time to provide you with important information, required notices and marketing promotions.',
            'For a better experience, while using the Application, the Service Provider may require you to provide us with certain personally identifiable information, including but not limited to email, name, location, camera. The information that the Service Provider request will be retained by them and used as described in this privacy policy.',
          ],
        },
      ],
    },
    {
      title: 'Third Party Access',
      paragraphs: [
        'Only aggregated, anonymized data is periodically transmitted to external services to aid the Service Provider in improving the Application and their service. The Service Provider may share your information with third parties in the ways that are described in this privacy statement.',
        'Please note that the Application utilizes third-party services that have their own Privacy Policy about handling data. Below are the links to the Privacy Policy of the third-party service providers used by the Application:',
      ],
      list: ['Expo'],
      subsections: [
        {
          title: 'Disclosure of Information',
          paragraphs: [
            'The Service Provider may disclose User Provided and Automatically Collected Information:',
            'as required by law, such as to comply with a subpoena, or similar legal process;',
            'when they believe in good faith that disclosure is necessary to protect their rights, protect your safety or the safety of others, investigate fraud, or respond to a government request;',
            'with their trusted services providers who work on their behalf, do not have an independent use of the information we disclose to them, and have agreed to adhere to the rules set forth in this privacy statement.',
          ],
        },
      ],
    },
    {
      title: 'Opt-Out Rights',
      paragraphs: [
        'You can stop all collection of information by the Application easily by uninstalling it. You may use the standard uninstall processes as may be available as part of your mobile device or via the mobile application marketplace or network.',
      ],
    },
    {
      title: 'Data Retention Policy',
      paragraphs: [
        "The Service Provider will retain User Provided data for as long as you use the Application and for a reasonable time thereafter. If you'd like them to delete User Provided Data that you have provided via the Application, please contact them at kinshipsync@gmail.com and they will respond in a reasonable time.",
      ],
    },
    {
      title: 'Children',
      paragraphs: [
        'The Service Provider does not use the Application to knowingly solicit data from or market to children under the age of 13.',
        'The Application does not address anyone under the age of 13. The Service Provider does not knowingly collect personally identifiable information from children under 13 years of age. In the case the Service Provider discover that a child under 13 has provided personal information, the Service Provider will immediately delete this from their servers. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact the Service Provider at kinshipsync@gmail.com so that they will be able to take the necessary actions.',
      ],
    },
    {
      title: 'Security',
      paragraphs: [
        'The Service Provider is concerned about safeguarding the confidentiality of your information. The Service Provider provides physical, electronic, and procedural safeguards to protect information the Service Provider processes and maintains.',
      ],
    },
    {
      title: 'Changes',
      paragraphs: [
        'This Privacy Policy may be updated from time to time for any reason. The Service Provider will notify you of any changes to the Privacy Policy by updating this page with the new Privacy Policy. You are advised to consult this Privacy Policy regularly for any changes, as continued use is deemed approval of all changes.',
      ],
    },
    {
      title: 'Your Consent',
      paragraphs: [
        'By using the Application, you are consenting to the processing of your information as set forth in this Privacy Policy now and as amended by us.',
      ],
    },
  ],
};

export const cookiePolicyDocument: LegalDocument = {
  slug: 'cookie-policy',
  title: 'Cookie Policy',
  subtitle: 'KinshipSync Web Application',
  metaDescription:
    'Understand how KinshipSync uses cookies and similar technologies on our website to improve your experience.',
  effectiveDate: '2025-08-03',
  intro:
    'This Cookie Policy explains how KinshipSync ("we", "us", or "our") uses cookies and similar tracking technologies when you visit our website and use our web application. By continuing to browse or use our services, you agree to our use of cookies as described in this policy.',
  contactEmail: 'kinshipsync@gmail.com',
  sections: [
    {
      title: 'What Are Cookies?',
      paragraphs: [
        'Cookies are small text files placed on your device when you visit a website. They help websites remember your preferences, keep you signed in, and understand how visitors interact with the site.',
        'We also use similar technologies such as local storage and session storage to support authentication and application functionality.',
      ],
    },
    {
      title: 'How We Use Cookies',
      paragraphs: ['KinshipSync uses cookies and similar technologies for the following purposes:'],
      list: [
        'Essential cookies — required for authentication, security, and core platform features such as event management and account access.',
        'Preference cookies — to remember your settings, such as theme preferences and display options.',
        'Analytics cookies — to understand how users interact with our website so we can improve performance and usability.',
        'Functional cookies — to enable features like notifications, form persistence, and session continuity.',
      ],
    },
    {
      title: 'Third-Party Cookies',
      paragraphs: [
        'Some cookies may be set by third-party services we use to operate KinshipSync, including authentication providers, analytics tools, and infrastructure services. These third parties have their own privacy and cookie policies governing how they handle data.',
      ],
      list: ['Firebase Authentication', 'Cloudinary (media hosting)', 'Analytics and performance monitoring services'],
    },
    {
      title: 'Managing Cookies',
      paragraphs: [
        'You can control and manage cookies through your browser settings. Most browsers allow you to refuse or delete cookies. Please note that disabling essential cookies may affect your ability to sign in or use certain features of KinshipSync.',
        'To manage cookies in your browser, refer to your browser\'s help documentation for instructions on blocking, deleting, or limiting cookies.',
      ],
    },
    {
      title: 'Updates to This Policy',
      paragraphs: [
        'We may update this Cookie Policy from time to time to reflect changes in technology, regulation, or our practices. We will post any updates on this page and revise the effective date accordingly.',
      ],
    },
  ],
};

export const termsOfServiceDocument: LegalDocument = {
  slug: 'terms-of-service',
  title: 'Terms of Service',
  subtitle: 'KinshipSync Platform',
  metaDescription:
    'Read the terms and conditions governing your use of the KinshipSync event planning platform.',
  effectiveDate: '2025-08-03',
  intro:
    'These Terms of Service ("Terms") govern your access to and use of the KinshipSync mobile application and web platform (collectively, the "Service") provided by Elropheka ("Company", "we", "us", or "our"). By creating an account or using the Service, you agree to be bound by these Terms.',
  contactEmail: 'support@kinshipsync.com',
  sections: [
    {
      title: 'Eligibility',
      paragraphs: [
        'You must be at least 13 years of age to use KinshipSync. If you are under 18, you represent that you have permission from a parent or guardian to use the Service. You are responsible for ensuring that your use of the Service complies with applicable laws in your jurisdiction.',
      ],
    },
    {
      title: 'Account Registration',
      paragraphs: [
        'To access certain features, you must create an account and provide accurate, complete information. You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account.',
        'You agree to notify us promptly of any unauthorized use of your account. We reserve the right to suspend or terminate accounts that violate these Terms or pose a security risk.',
      ],
    },
    {
      title: 'Use of the Service',
      paragraphs: ['KinshipSync enables users to plan events, manage guests, collaborate with family and friends, and connect with vendors. You agree not to:'],
      list: [
        'Use the Service for any unlawful, harmful, or fraudulent purpose.',
        'Upload or share content that infringes intellectual property rights or violates the privacy of others.',
        'Attempt to gain unauthorized access to other accounts, systems, or data.',
        'Interfere with or disrupt the integrity or performance of the Service.',
        'Use automated tools to scrape, harvest, or extract data without our written consent.',
      ],
    },
    {
      title: 'User Content',
      paragraphs: [
        'You retain ownership of content you create or upload to KinshipSync, including event details, images, and messages. By submitting content, you grant us a non-exclusive, worldwide license to host, display, and distribute that content solely to operate and improve the Service.',
        'You are solely responsible for the content you share and for obtaining any necessary permissions from guests, vendors, or other parties featured in your events.',
      ],
    },
    {
      title: 'Subscriptions and Payments',
      paragraphs: [
        'Certain features of KinshipSync may be offered on a freemium or paid subscription basis. Pricing, billing cycles, and included features are described at the time of purchase. All fees are non-refundable unless otherwise required by law or stated in a specific offer.',
        'We may change subscription plans or pricing with reasonable notice. Continued use of paid features after a price change constitutes acceptance of the new pricing.',
      ],
    },
    {
      title: 'Vendor Services',
      paragraphs: [
        'KinshipSync may facilitate connections between event organizers and third-party vendors. We do not guarantee the quality, availability, or performance of vendor services. Any agreements between you and a vendor are solely between you and that vendor.',
      ],
    },
    {
      title: 'Intellectual Property',
      paragraphs: [
        'The KinshipSync name, logo, software, design, and all related intellectual property are owned by Elropheka or its licensors. You may not copy, modify, distribute, or create derivative works from our Service without prior written permission.',
      ],
    },
    {
      title: 'Disclaimer of Warranties',
      paragraphs: [
        'The Service is provided on an "AS IS" and "AS AVAILABLE" basis without warranties of any kind, whether express or implied. We do not warrant that the Service will be uninterrupted, error-free, or free of harmful components.',
      ],
    },
    {
      title: 'Limitation of Liability',
      paragraphs: [
        'To the fullest extent permitted by law, Elropheka shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. Our total liability for any claim shall not exceed the amount you paid us in the twelve months preceding the claim, or fifty dollars (USD $50), whichever is greater.',
      ],
    },
    {
      title: 'Termination',
      paragraphs: [
        'You may stop using the Service at any time and may delete your account from your profile settings. We may suspend or terminate your access if you violate these Terms or if we discontinue the Service. Upon termination, your right to use the Service ceases immediately.',
      ],
    },
    {
      title: 'Changes to These Terms',
      paragraphs: [
        'We may modify these Terms at any time. We will post the updated Terms on this page and update the effective date. Your continued use of the Service after changes become effective constitutes acceptance of the revised Terms.',
      ],
    },
    {
      title: 'Governing Law',
      paragraphs: [
        'These Terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles. Any disputes arising under these Terms shall be resolved in the courts of competent jurisdiction.',
      ],
    },
  ],
};

export const legalDocuments = {
  privacyPolicy: privacyPolicyDocument,
  cookiePolicy: cookiePolicyDocument,
  termsOfService: termsOfServiceDocument,
} as const;

export const legalPageRoutes = {
  privacyPolicy: '/privacy-policy',
  termsOfService: '/terms-of-service',
  cookiePolicy: '/cookie-policy',
} as const;
